spring:
  application:
    name: cdn-user
  datasource:
    url: jdbc:mysql://172.28.64.35/ncdtp?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: cmcc2017
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


mybatis:
  mapper-locations: classpath:mapping/*.xml
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: false
    auto-mapping-behavior: partial
    safe-row-bounds-enabled: false
    local-cache-scope: session
    jdbc-type-for-null: other
    aggressive-lazy-loading: false
  type-handlers-package: github.zhangq.secretstringtest.config