spring:
  application:
    name: cdn-user
  datasource:
    url: jdbc:mysql://ipaddress/ncdtp?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: username
    password: password
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapping/*.xml
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: false
    auto-mapping-behavior: partial
    safe-row-bounds-enabled: false
    local-cache-scope: session
    jdbc-type-for-null: other
    aggressive-lazy-loading: false
  type-handlers-package: github.zhangq.secretstringtest.config