spring:
  application:
    name: cdn-user
  datasource:
    url: jdbc:mysql://ipaddress/ncdtp?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: username
    password: password
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-handlers-package: github.zhangq.secretstringtest.config